In [75]:
import pandas as pd
import numpy as np

In [2]:
## Question 1
pd.__version__

'2.3.1'

In [3]:
# !wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [5]:
df.head(10)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   
5                  190            3.0         NaN     2484.883986   
6                  240            7.0       127.0     3006.542287   
7                  150            4.0       239.0     3638.657780   
8                  250            1.0       174.0     2714.219310   
9                  150            4.0       123.0     3509.036569   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5          14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6          22.2        2012     USA  Gasoline  Front-wheel drive        1.0   
7          17.3        2020     USA    Diesel    All-wheel drive        1.0   
8          10.3        2016    Asia    Diesel  Front-wheel drive       -1.0   
9          10.2        2005     USA  Gasoline  Front-wheel drive       -1.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369  
5            17.271818  
6            13.210412  
7            12.848884  
8            16.823554  
9            12.298355

In [6]:
## Question 2
df.index

RangeIndex(start=0, stop=9704, step=1)

In [62]:
## Question 3
df['fuel_type'].nunique()

2

In [68]:
## Question 4
df.isnull().sum()[df.isnull().sum() > 0].shape[0]

3

In [9]:
## Question 5
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [10]:
## Question 6 -1
df['horsepower'].median()

np.float64(149.0)

In [70]:
## Question 6 -2
most_frequent = df['horsepower'].mode()[0]
print(most_frequent)

152.0


In [12]:
## Question 6 -3
df['horsepower'] = df['horsepower'].fillna(most_frequent)

In [13]:
## Question 6 - 4
df['horsepower'].median()

np.float64(152.0)

In [38]:
## Question 7 - 1
df_cars_asia = df[df['origin'] == 'Asia']
df_cars_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [41]:
## Question 7 - 2
df_filter_colms = df_cars_asia[['vehicle_weight', 'model_year']]
df_filter_colms

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [47]:
## Question 7 - 3
df_select_7_colms = df_filter_colms.head(7)
df_select_7_colms

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [85]:
## Question 7 - 4
X = df_select_7_colms.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [90]:
## Question 7 - 5
XTX = np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [93]:
## Question 7 - 6
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [97]:
## Question 7 - 7
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [107]:
## Question 7 - 8
w = np.dot(XTX_inv,X.T)
w

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [108]:
## Question 7 - 9
w_sum = np.dot(xy,y)
w_sum.sum()

np.float64(0.5187709081074016)